### PR TITLE
Adding StoreKit link and pre/post makefiles

### PR DESCRIPTION
**Pull request by jlyonsmith**
I fixed a bug and added pre/post build makefiles to pull the latest .zip file from Google and generated mdoc's.

### CODE REVIEW

**Comment by dalexsoto** [comment]
mmm, not sure if we should always get the latest build from google, what happens if binding gets outdated?

btw I love the idea of generating docs and thanks for the storeKit i missed it

@jiyonsmith I want to know your thoughts on getting the latest build from google. :)

Alex

**Comment by jlyonsmith** [comment]
Yeah, that's probably a bit too agressive :)  I'll fix it to just check and
give a warning in the csproj and tell you to run the makefile.  That sound
good?

John.

On Nov 22, 2012, at 7:56 AM, Alex Soto notifications@github.com wrote:

mmm, not sure if we should always get the latest build from google, what
happens if binding gets outdated?

btw I love the idea of generating docs and thanks for the storeKit i missed
it

I want to know your thoughts on getting the latest build from google. :)

Alex

—
Reply to this email directly or view it on
GitHubhttps://github.com/dalexsoto/AlexTouch.GoogleAdMobAds/pull/6#issuecomment-10638439.

**Comment by dalexsoto** [comment]
yeah that sounds good :)

**Comment by jlyonsmith** [comment]
OK, I've removed running the PreBuild.make in the .csproj

**Comment by dalexsoto** [comment]
Merged, thanks a lot :)

**Pull request merged**
